[project]
name = "mcp-jira"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.13",
    "fastmcp>=2.9.2",
    "openai>=1.93.0",
    "requests>=2.32.4",
]
